export enum TcgPokemonRarity {
  amazingRare = 'a',
  artRare = 'ar',
  common = 'c',
  characterHoloRare = 'chr',
  characterSuperRare = 'csr',
  doubleRare = 'rr',
  holoRare = 'hr',
  radiantRare = 'k',
  rare = 'r',
  rainbowRare = 'rar',
  secretRare = 'sr',
  shinyRare = 's',
  shinyUltraRare = 'ssr',
  specialArtRare = 'sar',
  tripleRare = 'rrr',
  ultraRare = 'ur',
  uncommon = 'u',
}
