export enum TcgPokemonRarity {
  amazingRare = 'amazingRare',
  artRare = 'artRare',
  common = 'common',
  characterHoloRare = 'characterHoloRare',
  characterSuperRare = 'characterSuperRare',
  doubleRare = 'doubleRare',
  holoRare = 'holoRare',
  radiantRare = 'radiantRare',
  rare = 'rare',
  rainbowRare = 'rainbowRare',
  secretRare = 'secretRare',
  shinyRare = 'shinyRare',
  shinyUltraRare = 'shinyUltraRare',
  specialArtRare = 'specialArtRare',
  tripleRare = 'tripleRare',
  ultraRare = 'ultraRare',
  uncommon = 'uncommon',
}
